# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-28 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, unique=True)),
                ('Topic', models.CharField(max_length=100, unique=True)),
                ('Teacher', models.CharField(max_length=100, unique=True)),
                ('Time', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
