# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-03 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='type',
            new_name='utype',
        ),
    ]
