# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-03 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='ProfileForm',
        ),
    ]
