# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-03 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20170703_1455'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileForm',
            new_name='Profile',
        ),
    ]
