# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-03 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20170703_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='user',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='utype',
            new_name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
