# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-03 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20170703_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='utype',
        ),
    ]
